theme: jekyll-theme-minimal
title: TP Interfaces - Duckade
author: Pedini Antonella, Santana Mariana 
description: Sitio web para las entregas de la materia Interfaces de Usuario e Interacción de segundo año de la carrera TUDAI. 
